name: Rust

on:
  push:
    branches: [ "master" , "rustServer" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
    - name: Build
      run: cargo build --verbose --manifest-path rust/Cargo.toml --release

    - name: List Files
      run: ls -R

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: virtualcanServer
        path: ${{ github.workspace }}/rust/target/release/virtualcan
